-- MySQL Script generated by MySQL Workbench
-- Wed Oct 18 23:43:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ECE1779A1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ECE1779A1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ECE1779A1` DEFAULT CHARACTER SET big5 ;
USE `ECE1779A1` ;

-- -----------------------------------------------------
-- Table `ECE1779A1`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECE1779A1`.`userinfo` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `usr_passwrd` VARCHAR(100) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECE1779A1`.`userimg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECE1779A1`.`userimg` (
  `uid` INT NULL,
  `img_id` INT NOT NULL AUTO_INCREMENT,
  `img_path` VARCHAR(200) NULL,
  `img0` VARCHAR(200) NULL,
  `img1` VARCHAR(200) NULL,
  `img2` VARCHAR(200) NULL,
  `img3` VARCHAR(200) NULL,
  PRIMARY KEY (`img_id`),
  INDEX `uid_idx` (`uid` ASC),
  CONSTRAINT `uid`
    FOREIGN KEY (`uid`)
    REFERENCES `ECE1779A1`.`userinfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

